version: "3.5"

services:
  nimiq-miner:
    image: pmietlicki/nimiq-miner
    volumes:
      - data:/home/nimiq
    deploy:
      resources:
        limits:
          cpus: '1.0'
      restart_policy:
        condition: on-failure
volumes:
  data:
